@baseUrl = http://localhost:8000
@urlPath = api/v1/auth

###
POST {{baseUrl}}/{{urlPath}}/sign-up
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Nimeshika1",
  "password": "nimenime1",
  "email": "nim1@test.com",
  "avatarColor": "blue",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA0gAAAMyAQMAAABtkHM/AAAABlBMVEUAAAD///+l2Z/dAAAAAXRSTlMAQObYZgAAAAFiS0dEAf8CLd4AAABrSURBVBgZ7cGBAAAAAMOg+1NP4AjVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjgBSwwABwrL8wAAAAABJRU5ErkJggg=="
}

###
POST {{baseUrl}}/{{urlPath}}/sign-in
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Nimeshika1",
  "password": "nimenime1"
}

###
GET {{baseUrl}}/{{urlPath}}/sign-out
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/current-user
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "nim@test.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2YzYjJhNDk4NzkzODhlMDkzNTg1NzAiLCJpYXQiOjE2NzY5MTU2ODQsImV4cCI6MTY3NjkxNTk4NH0.YPJ5KpHhmogb-cnzpx-Ewt5c0GobmrQXomvjXPBKLWw
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "newpassword",
  "confirmPassword": "newpassword"
}
